/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        error: '#ffb4ab',
        'secondary-fixed-dim': '#7bdb80',
        'on-background': '#dfe2eb',
        'surface-container-low': '#181c22',
        'primary-fixed': '#d3e4ff',
        'on-tertiary-container': '#4d3500',
        'surface-container-high': '#262a31',
        'surface-container-highest': '#31353c',
        'error-container': '#93000a',
        'secondary-fixed': '#97f999',
        'on-tertiary-fixed-variant': '#5f4100',
        'surface-dim': '#10141a',
        'on-surface-variant': '#c0c7d4',
        'secondary-container': '#007124',
        'on-primary-container': '#003a6b',
        'on-secondary-fixed-variant': '#005319',
        tertiary: '#fabc45',
        secondary: '#7bdb80',
        'surface-variant': '#31353c',
        'on-primary': '#00315c',
        'on-primary-fixed-variant': '#004882',
        'inverse-on-surface': '#2d3137',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#422c00',
        'inverse-primary': '#0060aa',
        primary: '#a2c9ff',
        'primary-container': '#58a6ff',
        'outline-variant': '#414752',
        'surface-container': '#1c2026',
        'on-tertiary-fixed': '#271900',
        background: '#10141a',
        'on-primary-fixed': '#001c38',
        'tertiary-fixed-dim': '#fabc45',
        'tertiary-fixed': '#ffdeaa',
        'surface-bright': '#353940',
        'on-error': '#690005',
        'inverse-surface': '#dfe2eb',
        outline: '#8b919d',
        'on-secondary-container': '#91f294',
        'tertiary-container': '#d29922',
        'on-secondary-fixed': '#002106',
        'on-surface': '#dfe2eb',
        'primary-fixed-dim': '#a2c9ff',
        'on-secondary': '#00390e',
        'surface-tint': '#a2c9ff',
        'surface-container-lowest': '#0a0e14',
        surface: '#10141a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        lg: '24px',
        sm: '8px',
        gutter: '16px',
        'margin-desktop': '32px',
        md: '16px',
        xs: '4px',
        xl: '32px',
        base: '4px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'code-md': ['JetBrains Mono'],
        'headline-md': ['Inter'],
        'label-caps': ['JetBrains Mono'],
        'display-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'body-lg': ['Inter'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'code-md': ['14px', { lineHeight: '20px', fontWeight: '450' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
